<?php

declare(strict_types=1);

/*
 * Implements hook_theme().
 */
function event_theme() : array {
  return [
    'event_page' => [
      'variables' => [
        'event' => '',
        'is_logged_in' => '',
        'registration_status' => '',
        'registration_message' => '',
        'register_button' => '',
        'participants_link' => '',
      ],
    ],
    'event_participants' => [
      'variables' => [
        'event' => '',
      ],
    ],
  ];
}

/**
 * Implements hook_cron().
 */
function event_cron() : void {
  \Drupal::service('event.event_status_cron')->run();
}
